### ISSUE TITLE
Can't start rodeo

### ISSUE THREAD

**Issue by abeburnett** [yhat/rodeo#114]
Hi there, I've recently installed Rodeo and was able to start it once. Now I'm unable to start it again. Can you please help? Here's the error I receive:

$ rodeo .
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\rodeo\kernel.py", line 3, in <module>
    from jupyter_client import BlockingKernelClient
ImportError: No module named 'jupyter_client'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python34\Scripts\rodeo-script.py", line 9, in <module>
    load_entry_point('rodeo==0.4.3', 'console_scripts', 'rodeo')()
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 519, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 2630, in load_entry_point
    return ep.load()
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 2310, in load
    return self.resolve()
  File "C:\Python34\lib\site-packages\pkg_resources\__init__.py", line 2316, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Python34\lib\site-packages\rodeo\cli.py", line 33, in <module>
    from .rodeo import main
  File "C:\Python34\lib\site-packages\rodeo\rodeo.py", line 2, in <module>
    from .kernel import Kernel
  File "C:\Python34\lib\site-packages\rodeo\kernel.py", line 5, in <module>
    from IPython.kernel import BlockingKernelClient
  File "C:\Python34\lib\site-packages\IPython\kernel\__init__.py", line 4, in <module>
    from . import zmq
  File "C:\Python34\lib\site-packages\IPython\kernel\zmq\__init__.py", line 8, in <module>
    check_for_zmq('13', 'IPython.kernel.zmq')
  File "C:\Python34\lib\site-packages\IPython\utils\zmqrelated.py", line 10, in check_for_zmq
    import zmq
  File "C:\Python34\lib\site-packages\zmq\__init__.py", line 42, in <module>
    _libsodium = ctypes.cdll.LoadLibrary(bundled_sodium[0])
  File "C:\Python34\lib\ctypes\__init__.py", line 429, in LoadLibrary
    return self._dlltype(name)
  File "C:\Python34\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 193] %1 is not a valid Win32 application

**Comment by abeburnett** [comment]
Never mind, this seems to have been resolved by completely uninstalling Python 3.4 and reinstalling. Ugh.
