### ISSUE TITLE
No module named ipykernel

### ISSUE THREAD

**Issue by ranio** [yhat/rodeo#127]
I'm new to iPython and Rodeo, today while I'm trying to launch Rodeo, I get the following warnings and error:
ipython notebook works good on my mac, it seems that Rodeo can display the type of object or even view the object, it's really attractive.
 
Vincents-MacBook-Pro:~ Vincent$ rodeo
/Library/Python/2.7/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.4.4', 'console_scripts', 'rodeo')()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 357, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2394, in load_entry_point
    return ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/Library/Python/2.7/site-packages/rodeo/cli.py", line 33, in <module>
    from .rodeo import main
  File "/Library/Python/2.7/site-packages/rodeo/rodeo.py", line 2, in <module>
    from .kernel import Kernel
  File "/Library/Python/2.7/site-packages/rodeo/kernel.py", line 5, in <module>
    from IPython.kernel import BlockingKernelClient
  File "/Library/Python/2.7/site-packages/IPython/kernel/__init__.py", line 31, in <module>
    from ipykernel import comm, inprocess
ImportError: No module named ipykernel

**Comment by metasyn** [comment]
I just found this as well

**Comment by torontodevelopers** [comment]
got around this by running:
sudo pip install jupyter

**Comment by ranio** [comment]
Thanks, it works for me

On Sat, Oct 3, 2015 at 8:34 AM, torontodevelopers <notifications@github.com>
wrote:

> got around this by running:
> sudo pip install jupyter
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/yhat/rodeo/issues/127#issuecomment-145188902>.
>



-- 
Liangliang Ren

**Comment by yotammanor** [comment]
This workaround works for me too, but I think this issue should be closed only after jupyter is included in Rodeo's dependencies, or otherwise solved. As of current date, the problem still occurs when following installation instructions, and this is a problem.

Other than that, looks cool, loads easily.

**Comment by QGB** [comment]
No jupyter, No ipykernel
