### ISSUE TITLE
File panel doesn't read files

### ISSUE THREAD

**Issue by jadianes** [yhat/rodeo#18]
Really cool IDE guys!  

One issue: I can read .py files when using the File menu dialog. However, if I click in the file name that appears in the file panel in at right-bottom, a new tab with the file name appears but looks empty. I've started the IDE just as explained in the quickstart and the files are those contained in the folder where I run `rodeo .`.  
  
![screen shot 2015-04-23 at 17 39 43](https://cloud.githubusercontent.com/assets/692262/7302229/cb5c191e-e9df-11e4-8a14-85d918c18754.png)

**Comment by glamp** [comment]
hmm that's odd. what OS are you using?

**Comment by jadianes** [comment]
Yosemite

**Comment by glamp** [comment]
what happens if you try to visit http://localhost:5000/file/enron_outliers.py in your browser?

**Comment by jadianes** [comment]
Hi @glamp,

I'll give it a try tomorrow. Thanks!  

Btw, is it possible to config the ide as a server and connect to it outside from local host? (As we do with IPython notebook).

**Comment by glamp** [comment]
yup https://github.com/yhat/rodeo/pull/28

**Comment by glamp** [comment]
i added some logging in the latest release 899a5c0eb8e586ac9fd75d69e9675bde8411c200

if you run `rodeo --verbose .` it will log what's happening w/r/t your files. hopefully this can shed some light on the issue!

**Comment by jadianes** [comment]
Tried without upgrading to go to [http://localhost:5000/file/enron_outliers.py](http://localhost:5000/file/enron_outliers.py), didn't load the page.   

Then upgraded. But when I tried `rodeo --verbose .` I got the following error trace:  

`
Traceback (most recent call last):
  File "/Users/jadianes/anaconda/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py", line 339, in load_entry_point
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py", line 2457, in load_entry_point
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/setuptools-5.8-py2.7.egg/pkg_resources.py", line 2171, in load
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/rodeo/cli.py", line 30, in <module>
    from rodeo import main
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/rodeo/rodeo.py", line 1, in <module>
    from .kernel import Kernel
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/rodeo/kernel.py", line 5, in <module>
    from IPython.kernel import BlockingKernelClient
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/IPython/kernel/__init__.py", line 4, in <module>
    from . import zmq
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/IPython/kernel/zmq/__init__.py", line 8, in <module>
    check_for_zmq('13', 'IPython.kernel.zmq')
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/IPython/utils/zmqrelated.py", line 10, in check_for_zmq
    import zmq
  File "/Users/jadianes/anaconda/lib/python2.7/site-packages/zmq/__init__.py", line 32, in <module>
    _libzmq = ctypes.CDLL(bundled[0], mode=ctypes.RTLD_GLOBAL)
  File "/Users/jadianes/anaconda/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: dlopen(/Users/jadianes/anaconda/lib/python2.7/site-packages/zmq/libzmq.so, 10): Symbol not found: __ZNSs4_Rep20_S_empty_rep_storageE
  Referenced from: /Users/jadianes/anaconda/lib/python2.7/site-packages/zmq/libzmq.so
  Expected in: dynamic lookup
`

**Comment by glamp** [comment]
woof. not sure what to make of that. maybe remove `zmq` and reinstall it?
