### ISSUE TITLE
Problem with completion on OSX

### ISSUE THREAD

**Issue by dputhier** [yhat/rodeo#195]
Hello,
I'm using Rodeo v1.1.21 on OSX 10.10. When trying to get completion with tab key, I get the following error message.
Best

Uncaught Exception:
SyntaxError: Unexpected token 
    at Object.parse (native)
    at Stream.<anonymous> (/Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:73:27)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at emitToken (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:23:21)
    at doSplit (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:29:9)
    at Stream.stream.write (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:46:7)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

**Comment by glamp** [comment]
fixed in 1.3
