### ISSUE TITLE
DistributionNotFound Error on Ubuntu

### ISSUE THREAD

**Issue by thedon16** [yhat/rodeo#202]
I installed Rodeo successfully using:

```sudo pip install rodeo```

But when I run:

```sudo rodeo .```

I get the error below.  Any advice??

Using Ubuntu 14.04 64-bit.

```Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 444, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 725, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: simplegeneric>0.8```

**Comment by glamp** [comment]
The distribution on pip is being deprecated.

See [here](yhat.com/products/rodeo/downloads) for up to date downloads
