### ISSUE TITLE
'ascii' codec can't decode 

### ISSUE THREAD

**Issue by chakwing** [yhat/rodeo#234]
**UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 2: ordinal not in range(12**8)

yesterday, I installed and it worked well.  This morning, I had a system update (the usual rolling update you get from Ubuntu)-my distro is U15.10. This error appeared.  I installed same on a 14.04 Ubuntu-mate, It too underwent system update yesterday which called me to update grub.  It worked as I install it but the same error message appears

**Comment by glamp** [comment]
Can you post a screenshot?

**Comment by chakwing** [comment]
certainly, but I found out the problem was caused by two names I used in one of the file folder; which contain Chinese characters.  And there were several hidden "/.file." also with a few Chinese characters as its file name.  After I deleted these names/files, 'Rodeo' starts all right.  I guess I might as well close this thread.  
screen dump:
Can't display file: bt與ffn 類/2015-12-26 try bt in notebook.ipynb. It has non-ascii characters in the filename.
Can't display file: bt與ffn 類/.ipynb_checkpoints/2015-12-26 try bt in notebook-checkpoint.ipynb. It has non-ascii characters in the filename.
[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/rodeo/rodeo.py", line 79, in home
    file_tree=file_tree, version=__version__)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/index.html", line 34, in top-level template code
    {% include 'bottom-right.html' %}
  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/bottom-right.html", line 17, in top-level template code
    <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" href="#" class="list-group-item {{ f.parentslug }} showdir">
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe8 in position 2: ordinal not in range(128)

My apologies for this late reply.

**Comment by chakwing** [comment]
same issue again:
 _______      ___   ______   ________    ___    
|_   __ \   .'   `.|_   _ `.|_   __  | .'   `.  
  | |__) | /  .-.  \ | | `. \ | |_ \_|/  .-.  \ 
  |  __ /  | |   | | | |  | | |  _| _ | |   | | 
 _| |  \ \_\  `-'  /_| |_.' /_| |__/ |\  `-'  / 
|____| |___|`.___.'|______.'|________| `.___.'  

''''''''''''''''''''''''''''''''''''''''''''''''''
  URL: http://localhost:5000/
  DIRECTORY: /home/zerongx
''''''''''''''''''''''''''''''''''''''''''''''''''
[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/rodeo/rodeo.py", line 79, in home
    file_tree=file_tree, version=__version__)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/index.html", line 34, in top-level template code
    {% include 'bottom-right.html' %}
  File "/usr/local/lib/python2.7/dist-packages/rodeo/templates/bottom-right.html", line 17, in top-level template code
    <a id="file-{{ f.dirname }}" data-parnet-slug="{{ f.parentslug }}" data-dirname="{{ f.dirslug }}" href="#" class="list-group-item {{ f.parentslug }} showdir">
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe6 in position 0: ordinal not in range(128)

What's wrong??

**Comment by chakwing** [comment]
I'm sorry, I forgot to capture a snapshot.  The browser just say "internal error".
