### ISSUE TITLE
rodeo command return error

### ISSUE THREAD

**Issue by VedAustin** [yhat/rodeo#25]
Installed rodeo via the pip command on Win 8.1 (64 bit) machine. Ran the command on 'cygwin':
```rodeo .``` and was returned the following error:
```
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\cygwin64\\tmp\\kernel-b66e5ff6-2600-4a33-9f83-4889bf4b73f1.json'
```
Note: Latest Anaconda package was installed

**Comment by dpipkin** [comment]
I'm getting a similar error with [Cmder](http://gooseberrycreative.com/cmder/). It works fine with cmd though.

**Comment by andmalc** [comment]
Same thing on Debian Jesse 
  
Traceback (most recent call last):
  File "/home/andmalc/Envs/rodeo/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.1', 'console_scripts', 'rodeo')()
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/rodeo/cli.py", line 41, in cmd
    main(active_dir)
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 72, in main
    kernel = Kernel()
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/rodeo/kernel.py", line 91, in __init__
    self.client.load_connection_file()
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/IPython/kernel/connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'/tmp/kernel-32432339-9d48-421e-a894-acef07846d65.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/rodeo/kernel.py", line 83, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/tmp/kernel-32432339-9d48-421e-a894-acef07846d65.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/home/andmalc/Envs/rodeo/local/lib/python2.7/site-packages/rodeo/kernel.py", line 83, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/tmp/kernel-32432339-9d48-421e-a894-acef07846d65.json'

**Comment by wlblount** [comment]
got this error in power shell

PS C:\> rodeo .
Traceback (most recent call last):
  File "C:\Users\Bill\Anaconda\Scripts\rodeo-script.py", line 9, in <module>
    load_entry_point('rodeo==0.2.1', 'console_scripts', 'rodeo')()
  File "C:\Users\Bill\Anaconda\lib\site-packages\rodeo\cli.py", line 41, in cmd
    main(active_dir)
  File "C:\Users\Bill\Anaconda\lib\site-packages\rodeo\rodeo.py", line 72, in main
    kernel = Kernel()
  File "C:\Users\Bill\Anaconda\lib\site-packages\rodeo\kernel.py", line 91, in __init__
    self.client.load_connection_file()
  File "C:\Users\Bill\Anaconda\lib\site-packages\IPython\kernel\connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'c:\\users\\bill\\appdata\\local\\temp\\kernel-1b40d7a4-16aa-4f29-b8db-fa
65f6df6981.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Bill\Anaconda\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Users\Bill\Anaconda\lib\site-packages\rodeo\kernel.py", line 83, in remove_config
    os.remove(config)
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\users\\bill\\appdata\\local\\temp\\kernel-1b40d7
a4-16aa-4f29-b8db-fa65f6df6981.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\Users\Bill\Anaconda\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\Users\Bill\Anaconda\lib\site-packages\rodeo\kernel.py", line 83, in remove_config
    os.remove(config)
WindowsError: [Error 2] The system cannot find the file specified: 'c:\\users\\bill\\appdata\\local\\temp\\kernel-1b40d7
a4-16aa-4f29-b8db-fa65f6df6981.json'
PS C:\>

**Comment by ogrisel** [comment]
Please edit your issue and comments to put triple back-ticks signs around the quoted tracebacks and other commands to make them more readable on github. See https://guides.github.com/features/mastering-markdown/ .

**Comment by glamp** [comment]
no longer saving the kernel.json file to a temp directory so this particular issue is resolved (though you may still get errors with anaconda)

**Comment by VedAustin** [comment]
No longer saves in the temp folder. But as you said, it still gives me an error with anaconda.
``` WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\Austin\\Anaconda\\.kernel-5019ace8-02e1-4272-ac10-2b230462c164.json' ```
