### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by chrisalbon** [yhat/rodeo#26]
I'm getting a missing file-folder error when trying to run Rodeo on both py2 and py3 environments

```
(py3k)Christophers-MacBook-Pro:~ chrisralbon$ rodeo .
Traceback (most recent call last):
  File "/Users/chrisralbon/anaconda/envs/py3k/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.1', 'console_scripts', 'rodeo')()
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/rodeo/cli.py", line 41, in cmd
    main(active_dir)
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/rodeo/rodeo.py", line 72, in main
    kernel = Kernel()
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/rodeo/kernel.py", line 91, in __init__
    self.client.load_connection_file()
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/IPython/kernel/connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/l_/t7xb0srs2vl248mf61063b840000gn/T/kernel-f4f55455-1347-4607-8131-262c14871d33.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/chrisralbon/anaconda/envs/py3k/lib/python3.4/site-packages/rodeo/kernel.py", line 83, in remove_config
    os.remove(config)
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/l_/t7xb0srs2vl248mf61063b840000gn/T/kernel-f4f55455-1347-4607-8131-262c14871d33.json'
(py3k)Christophers-MacBook-Pro:~ chrisralbon$ 
```

**Comment by glamp** [comment]
What OS?

**Comment by chrisalbon** [comment]
OSX Yosemite 10.10.3

**Comment by DanielShestakov** [comment]
Same error on Ubuntu 15.04 with Anaconda Python 2.7

**Comment by chrisalbon** [comment]
I think this issue might be related or the same to https://github.com/yhat/rodeo/issues/49

**Comment by eli-b** [comment]
I'm getting a similar error on Windows 8.1 (also using anaconda):
C:\Users\USER>rodeo .
Traceback (most recent call last):
  File "C:\ANACONDA\SCRIPTS\rodeo-script.py", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "C:\ANACONDA\lib\site-packages\rodeo\cli.py", line 56, in cmd
    main(active_dir, port=port, host=host, browser=browser)
  File "C:\ANACONDA\lib\site-packages\rodeo\rodeo.py", line 85, in main
    kernel = Kernel(active_dir)
  File "C:\ANACONDA\lib\site-packages\rodeo\kernel.py", line 81, in __init__
    self.client.load_connection_file()
  File "C:\ANACONDA\lib\site-packages\IPython\kernel\connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'C:\\Users\\USER\\.kernel-7a5d91c6-f98c-4279-a5bb-7490cde64019.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\ANACONDA\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\ANACONDA\lib\site-packages\rodeo\kernel.py", line 73, in remove_config
    os.remove(config)
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\USER\\.kernel-7a5d91c6-f98c-4279-a5bb-7490cde64019.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "C:\ANACONDA\lib\atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "C:\ANACONDA\lib\site-packages\rodeo\kernel.py", line 73, in remove_config
    os.remove(config)
WindowsError: [Error 2] The system cannot find the file specified: 'C:\\Users\\USER\\.kernel-7a5d91c6-f98c-4279-a5bb-7490cde64019.json'

**Comment by glamp** [comment]
i added some logging in the latest release 899a5c0eb8e586ac9fd75d69e9675bde8411c200

if you run `rodeo --verbose .` it will log what's happening w/r/t your files. hopefully this can shed some light on the issue!

**Comment by rilut** [comment]
Me too on Anaconda 3 and Windows 10 TP

**Comment by glamp** [comment]
should be fixed

**Comment by rilut** [comment]
:+1: Confirmed to worked on Anaconda 3.0 in Windows 10 x64

**Comment by glamp** [comment]
:tada:
