### ISSUE TITLE
Linux binary exits right after being executed

### ISSUE THREAD

**Issue by rguerra** [yhat/rodeo#261]
Hi,

I want to run Rodeo as a remote server in an Ubuntu Server running:
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.4 LTS
Release:	14.04
Codename:	trusty

I downloaded the binary. When I run the Rodeo binary it immediately exits without doing anything. I have no I idea on how to run the Rodeo server only. The rodeo command line bash script [here](https://raw.githubusercontent.com/yhat/rodeo/master/bin/rodeo) doesn't work since it assumes something is installed in: /tmp/rodeo-build/Rodeo/rodeo

I spent sometime manually trying to run bin/rodeo-web, but it was a nightmare. It is trying to look for functions that don't exist in src/rodeo/kernel

**Comment by thuyen** [comment]
I have the same problem on Ubuntu 14.04. I can start Rodeo for the first time after logging in. But after that, the application exits immediately every time I I run it. 

Rodeo log: 

2016-07-08T15:19:54.099Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onGetResponseDetails { code: 200,
  url: 'http://rodeo-analytics.yhathq.com/?an=Rodeo&av=2.0.5&cid=f8b9fd5c-8849-19c2-5d0c-a5e1ea8e4964&ec=kernel&ea=kernel_detected' }
2016-07-08T15:19:54.100Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 13 shareAction undefined
2016-07-08T15:19:54.913Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed ElectronEvent { sender: WebContents { title: undefined, url: undefined } }
2016-07-08T15:19:54.914Z - warn: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed failed to iterate through window references
2016-07-08T15:19:54.956Z - info: ../opt/Rodeo/resources/app/node/index:: quit { errorCode: 1 }
2016-07-08T15:19:54.958Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed ElectronEvent { sender: WebContents { title: undefined, url: undefined } }
2016-07-08T15:19:54.961Z - warn: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed failed to iterate through window references

**Comment by TakenPilot** [comment]
Thanks for the info!

Could you include more of the log?  It's likely that there is an error earlier in the log that's causing it to abort the startup.

I don't have much UI messaging around errors on startup yet, but there is a ton of logging.

**Comment by thuyen** [comment]
Sorry, it's my bad habit just looking at the tail of the log. It seems Rodeo couldn't access port 9356 at subsequent runs. 

2016-07-08T22:36:30.629Z - error: uncaughtException: listen EADDRINUSE :::9356 
{ date: 'Fri Jul 08 2016 15:36:30 GMT-0700 (PDT)',
  process: 
   { pid: 6305,
     uid: 1362258672,
     gid: 500,
     cwd: '/',
     execPath: '/opt/Rodeo/Rodeo',
     version: 'v6.1.0',
     argv: [ '/opt/Rodeo/Rodeo' ],
     memoryUsage: { rss: 75137024, heapTotal: 36741120, heapUsed: 19481104 } },
  os: 
   { loadavg: [ 0.1630859375, 0.05810546875, 0.09521484375 ],
     uptime: 185357 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'Object.exports._errnoException',
       line: 949,
       method: 'exports._errnoException',
       native: false },
     { column: 20,
       file: 'util.js',
       function: 'exports._exceptionWithHostPort',
       line: 972,
       method: '_exceptionWithHostPort',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'Server._listen2',
       line: 1253,
       method: '_listen2',
       native: false },
     { column: 10,
       file: 'net.js',
       function: 'listen',
       line: 1289,
       method: null,
       native: false },
     { column: 5,
       file: 'net.js',
       function: 'Server.listen',
       line: 1385,
       method: 'listen',
       native: false },
     { column: 24,
       file: '/opt/Rodeo/resources/app/node_modules/express/lib/application.js',
       function: 'EventEmitter.listen',
       line: 617,
       method: 'listen',
       native: false },
     { column: 9,
       file: '/opt/Rodeo/resources/app/node/services/server.js',
       function: null,
       line: 16,
       method: null,
       native: false },
     { column: 9,
       file: '/opt/Rodeo/resources/app/node_modules/bluebird/js/release/debuggability.js',
       function: 'Promise._execute',
       line: 272,
       method: '_execute',
       native: false },
     { column: 18,
       file: '/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js',
       function: 'Promise._resolveFromExecutor',
       line: 475,
       method: '_resolveFromExecutor',
       native: false },
     { column: 14,
       file: '/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js',
       function: 'new Promise',
       line: 77,
       method: null,
       native: false },
     { column: 10,
       file: '/opt/Rodeo/resources/app/node/services/server.js',
       function: 'Object.start',
       line: 13,
       method: 'start',
       native: false },
     { column: 34,
       file: '/opt/Rodeo/resources/app/node/index.js',
       function: 'attachAppEvents',
       line: 759,
       method: null,
       native: false },
     { column: 1,
       file: '/opt/Rodeo/resources/app/node/index.js',
       function: '',
       line: 788,
       method: null,
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module._compile',
       line: 541,
       method: '_compile',
       native: false },
     { column: 10,
       file: 'module.js',
       function: 'Object.Module._extensions..js',
       line: 550,
       method: 'Module._extensions..js',
       native: false },
     { column: 32,
       file: 'module.js',
       function: 'Module.load',
       line: 456,
       method: 'load',
       native: false } ],
  stack: 
   [ 'Error: listen EADDRINUSE :::9356',
     '    at Object.exports._errnoException (util.js:949:11)',
     '    at exports._exceptionWithHostPort (util.js:972:20)',
     '    at Server._listen2 (net.js:1253:14)',
     '    at listen (net.js:1289:10)',
     '    at Server.listen (net.js:1385:5)',
     '    at EventEmitter.listen (/opt/Rodeo/resources/app/node_modules/express/lib/application.js:617:24)',
     '    at /opt/Rodeo/resources/app/node/services/server.js:16:9',
     '    at Promise._execute (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/debuggability.js:272:9)',
     '    at Promise._resolveFromExecutor (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:475:18)',
     '    at new Promise (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:77:14)',
     '    at Object.start (/opt/Rodeo/resources/app/node/services/server.js:13:10)',
     '    at attachAppEvents (/opt/Rodeo/resources/app/node/index.js:759:34)',
     '    at Object.<anonymous> (/opt/Rodeo/resources/app/node/index.js:788:1)',
     '    at Module._compile (module.js:541:32)',
     '    at Object.Module._extensions..js (module.js:550:10)',
     '    at Module.load (module.js:456:32)' ] }
2016-07-08T22:36:30.827Z - info: ../opt/Rodeo/resources/app/node/index:: will-finish-launching

**Comment by thuyen** [comment]
killall Rodeo does the job. 

The real problem for me is Rodeo couldn't restart the kernel. Whenever I press Ctr+R, the message "restarting terminal... " stays forever. I need to close Rodeo, but somehow it's still running in background. 

The log when I try to restart the kernel: 

2016-07-08T23:30:15.064Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onGetResponseDetails { code: 200,
  url: 'http://rodeo-analytics.yhathq.com/?an=Rodeo&av=2.0.5&cid=f8b9fd5c-8849-19c2-5d0c-a5e1ea8e4964&ec=kernel&ea=kernel_detected' }
2016-07-08T23:30:15.065Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onGetResponseDetails { code: 200,
  url: 'http://rodeo-analytics.yhathq.com/?an=Rodeo&av=2.0.5&cid=f8b9fd5c-8849-19c2-5d0c-a5e1ea8e4964&ec=kernel&ea=kernel_detected' }
2016-07-08T23:30:15.065Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 5 shareAction undefined
2016-07-08T23:30:15.769Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 6 shareAction { '0': { type: 'CLOSING_WINDOW' } }
2016-07-08T23:30:15.771Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 7 closeWindow { '0': 'startupWindow' }
2016-07-08T23:30:15.772Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onClose
2016-07-08T23:30:15.792Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed ElectronEvent { sender: WebContents { title: undefined, url: undefined } }
2016-07-08T23:30:15.793Z - warn: ../opt/Rodeo/resources/app/node/services/browser-windows:: onDestroyed failed to iterate through window references
2016-07-08T23:30:15.795Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 6 shareAction undefined
2016-07-08T23:30:15.796Z - error: ../opt/Rodeo/resources/app/node/services/ipc-promises:: failed to reply to event 6 shareAction undefined 'Error: Object has been destroyed\n    at Error (native)\n    at sendWrapper (/opt/Rodeo/resources/electron.asar/browser/api/web-contents.js:107:24)\n    at /opt/Rodeo/resources/app/node/services/ipc-promises.js:23:22\n    at tryCatcher (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:504:31)\n    at Promise._settlePromise (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:561:18)\n    at Promise._settlePromiseCtx (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:598:10)\n    at Async._drainQueue (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:143:12)\n    at Async._drainQueues (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:17:14)\n    at tryOnImmediate (timers.js:543:15)\n    at processImmediate [as _immediateCallback] (timers.js:523:5)'
2016-07-08T23:30:15.797Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 7 closeWindow undefined
2016-07-08T23:30:15.798Z - error: ../opt/Rodeo/resources/app/node/services/ipc-promises:: failed to reply to event 7 closeWindow undefined 'Error: Object has been destroyed\n    at Error (native)\n    at sendWrapper (/opt/Rodeo/resources/electron.asar/browser/api/web-contents.js:107:24)\n    at /opt/Rodeo/resources/app/node/services/ipc-promises.js:23:22\n    at tryCatcher (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:504:31)\n    at Promise._settlePromise (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:561:18)\n    at Promise._settlePromiseCtx (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:598:10)\n    at Async._drainQueue (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:143:12)\n    at Async._drainQueues (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:17:14)\n    at tryOnImmediate (timers.js:543:15)\n    at processImmediate [as _immediateCallback] (timers.js:523:5)'
2016-07-08T23:30:15.859Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: show
2016-07-08T23:30:19.818Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 14 createKernelInstance { '0': { cmd: '/home/tngo/.virtualenvs/nnet/bin/python' } }
2016-07-08T23:30:19.834Z - info: ../opt/Rodeo/resources/app/node/index:: created new python kernel process ciqedknqj000z9jjc1vcf08gx { cmd: '/home/tngo/.virtualenvs/nnet/bin/python' }
2016-07-08T23:30:21.748Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 14 createKernelInstance ciqedknqj000z9jjc1vcf08gx
2016-07-08T23:30:21.767Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 15 killKernelInstance { '0': 'ciqedknqj000z9jjc1vcf08gx' }
2016-07-08T23:30:21.767Z - info: ../opt/Rodeo/resources/app/node/index:: deleted python kernel process reference ciqedknqj000z9jjc1vcf08gx
2016-07-08T23:30:21.770Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 16 shareAction { '0': { executionState: 'busy', type: 'IOPUB_STATE_CHANGED' } }
2016-07-08T23:30:21.772Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 16 shareAction undefined
2016-07-08T23:30:26.780Z - error: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event failed 15 killKernelInstance 'TimeoutError: failed to kill child process 10799\n    at afterTimeout (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-08T23:30:26.789Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 17 getAppVersion {}
2016-07-08T23:30:26.790Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 17 getAppVersion 2.0.5
2016-07-08T23:30:26.792Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: responding to ipc event 18 shareAction { '0': { error: {}, type: 'ERROR_CAUGHT' } }
2016-07-08T23:30:26.793Z - info: ../opt/Rodeo/resources/app/node/services/ipc-promises:: event succeeded 18 shareAction undefined
2016-07-08T23:30:26.798Z - info: ../opt/Rodeo/resources/app/node/services/browser-windows:: onGetResponseDetails { code: 200,
  url: 'http://rodeo-analytics.yhathq.com/?an=Rodeo&av=2.0.5&cid=f8b9fd5c-8849-19c2-5d0c-a5e1ea8e4964&ec=application&ea=error_caught' }

**Comment by TakenPilot** [comment]
`TimeoutError: failed to kill child process 10799`

Seems like this is the main issue.  For whatever reason, processes are refusing to die on linux.

**Comment by Robsteranium** [comment]
It looks like the `renderer` and `gpu-process` finish but the following processes remain:

    /opt/Rodeo/Rodeo
    /opt/Rodeo/Rodeo --type=zygote --no-sandbox
    /usr/bin/python3 /opt/Rodeo/resources/app/node/kernels/python/start_kernel.py
    
Kubuntu 16.04 Xenial
Rodeo 2.0.10
Python 3.5.2

**Comment by TakenPilot** [comment]
In [v2.1.3](https://github.com/yhat/rodeo/releases/tag/v2.1.3), all the processes are explicitly killed before the main process, if the main process is told to exit or quit from the window, the menu, or the keyboard shortcut.

Does it work for you?

**Comment by Robsteranium** [comment]
v2.1.3 resolves this for me - those Rodeo and python processing no longer remain after exit. Thanks!
