### ISSUE TITLE
Issue Mac 10.10.5

### ISSUE THREAD

**Issue by franinsu** [yhat/rodeo#334]
Using rodeo, when I open it I get:
Uncaught Exception:
SyntaxError: Unexpected number
    at Object.parse (native)
    at Stream.<anonymous> (/Applications/Rodeo.app/Contents/Resources/app.asar/src/rodeo/kernel.js:68:25)
    at emitOne (events.js:77:13)
    at Stream.emit (events.js:169:7)
    at emitToken (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:23:21)
    at doSplit (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:29:9)
    at Stream.stream.write (/Applications/Rodeo.app/Contents/Resources/app.asar/node_modules/stream-splitter/lib/splitter.js:46:7)
    at Socket.ondata (_stream_readable.js:525:20)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)

I get this error twice.

I can still enter the interface, but apart from editing, opening and saving files, all the execution things, and the console don't work.

**Comment by coristig** [comment]
@franinsu are you running the latest version (1.4.9)?  

Its available here: https://github.com/yhat/rodeo/releases

**Comment by franinsu** [comment]
I wasn't, but I downloaded it and it fixed the problem.
Thanks
