### ISSUE TITLE
Get "UnicodeDecodeError" while installing rodeo

### ISSUE THREAD

**Issue by gepcel** [yhat/rodeo#35]
When I tryed to install rodeo, I got an error as following:

```python
   C:\Documents and Settings\wayangel\desktop\rodeo-master>python setup.py install
Traceback (most recent call last):
  File "setup.py", line 44, in <module>
    long_description=open("README.rst").read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0x98 in position 1106: illegal
 multibyte sequence
```

Changing that line to `long_description=open("README.rst", encoding='utf8').read()` seems working.

**Comment by glamp** [comment]
What is in position 1106?

**Comment by gepcel** [comment]
Sorry, I don't know. Can you show me how to find out ? I'm not an expert.

**Comment by avptin** [comment]
I see the similar issue:
```
C:\>python -m pip install -U rodeo
Collecting rodeo
  Using cached rodeo-0.2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Oleksiy\AppData\Local\Temp\pip-build-awnjnymg\rodeo\setup.p
y", line 44, in <module>
        long_description=open("README.rst").read(),
      File "C:\Python34\lib\encodings\cp1251.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x98 in position 1106:
 character maps to <undefined>
```

**Comment by glamp** [comment]
oh i think it's the "⌘" in the readme. i'lll add the UTF encoding.
722795487e0011411677e5ce4cf648fb0b535922

**Comment by avptin** [comment]
It works now. Thank you.
