### ISSUE TITLE
Can't import pandas

### ISSUE THREAD

**Issue by drsnyder** [yhat/rodeo#396]
I'm starting off with this file but when I run the first link it hangs there in the console. I got impatient after several minutes and closed rodeo. I did this several times and I was unable to move past the first line.

```
import pandas as pd
```

I'm using OS X version `10.11.5 (15F34)`.

**Comment by TakenPilot** [comment]
Hi,

Which version of Rodeo were you running?

What do the logs (in the home directory) say?

**Comment by drsnyder** [comment]
I'm using 2.0.13. Here is what came through the log

```
2016-07-27T00:07:30.585Z - info: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: responding to ipc event 41 execute { '0': { instanceId: 'cir44s11i0008nuxwhn6est44' },
  '1': 'import pandas as pd' }
2016-07-27T00:07:30.585Z - info: Applications/Rodeo.app/Contents/Resources/app/node/index:: getKernelInstanceById cir44s11i0008nuxwhn6est44
2016-07-27T00:07:30.734Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 22 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:30.839Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 23 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:30.975Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 24 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.214Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 25 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.303Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 26 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.455Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 27 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.554Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 28 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.742Z - info: Applications/Rodeo.app/Contents/Resources/app/node/services/browser-windows:: blur mainWindow
2016-07-27T00:07:31.750Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 29 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:31.849Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 30 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.073Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 31 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.267Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 32 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.401Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 33 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.501Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 34 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.557Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 35 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.738Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 36 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:32.940Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 37 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:33.468Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 38 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:33.700Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 39 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:33.781Z - error: Applications/Rodeo.app/Contents/Resources/app/node/services/ipc-promises:: event failed 40 getAutoComplete 'TimeoutError: AutoComplete failed to finish in 5 seconds\n    at afterTimeout (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:48:15)\n    at Timeout.timeoutTimeout [as _onTimeout] (/Applications/Rodeo.app/Contents/Resources/app/node_modules/bluebird/js/release/timers.js:75:13)\n    at tryOnTimeout (timers.js:224:11)\n    at Timer.listOnTimeout (timers.js:198:5)'
2016-07-27T00:07:34.553Z - info: Applications/Rodeo.app/Contents/Resources/app/node/services/browser-windows:: hide mainWindow

```

**Comment by TakenPilot** [comment]
Yeah, looks like there might be other errors happening, leading to the kernel just not being available.

There are two places for logs.  One is in your home directory in `rodeo.log`, because there are so many processes (the IPython/Jupyter kernel, the python process running the kernel, Node.js serving the plots in a memory-safe way, each Chromium browser window...) that that's the only safe place I could reliably put those.  The other place is in the Dev Tools console available from the Rodeo menu.  Eventually I'm going to consolidate them in a kind of "Events Log" UI like PyCharm and Atom does.

Anyway, in one of those two places, there will be an explanation of specialness going on with your python installation.  I'm really interested in these use cases because 1) they're actually really rare, and 2) I really want to fix them.  😄

**Comment by drsnyder** [comment]
OK, well I need to apologize. I was using my stock python installation instead of my "data science" virtual environment that includes pandas. Once I switched the python configuration it worked fine.

That said, it does seem like there is something missing in the error logs. Neither the console in the Rodeo UI nor the `rodeo.log` included anything that hinted at pandas not being installed.

Thanks for the quick response. I look forward to using it!

**Comment by pgensler** [comment]
I know this issue is closed, but I'm experiencing the same issue with Rodeo, and not sure what to do. I'd love to help in any way, so let me know what you need from my end. I'm using 2.4.2 on OS X 10.12

**Comment by drsnyder** [comment]
@pgensler All I had to do was change the python path in the rodeo configuration. I used the path to the python binary in a virtualenv that I created that has all of the prerequisite packages installed.

After I made the change it worked as expected.
