### ISSUE TITLE
Crashed on startup with exception

### ISSUE THREAD

**Issue by Vimos** [yhat/rodeo#443]
➜  Rodeo ./Rodeo 
error: uncaughtException: listen EADDRINUSE :::9356 date=Tue Aug 30 2016 14:18:14 GMT+0800 (CST), pid=21420, uid=1000, gid=1000, cwd=/opt/Rodeo, execPath=/opt/Rodeo/Rodeo, version=v6.1.0, argv=[/opt/Rodeo/Rodeo], rss=76107776, heapTotal=27303936, heapUsed=19576576, loadavg=[1.6904296875, 2.2021484375, 2.14697265625], uptime=100301
Error: listen EADDRINUSE :::9356
    at Object.exports._errnoException (util.js:949:11)
    at exports._exceptionWithHostPort (util.js:972:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at Server.listen (net.js:1385:5)
    at EventEmitter.listen (/opt/Rodeo/resources/app/node_modules/express/lib/application.js:617:24)
    at /opt/Rodeo/resources/app/node/services/server.js:16:9
    at Promise._execute (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:475:18)
    at new Promise (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:77:14)
    at Object.start (/opt/Rodeo/resources/app/node/services/server.js:13:10)
    at attachAppEvents (/opt/Rodeo/resources/app/node/index.js:782:34)
    at Object.<anonymous> (/opt/Rodeo/resources/app/node/index.js:811:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)

**Comment by TakenPilot** [comment]
Thanks!

This exception is caused by Rodeo trying to use a port that something else is using, and falling on its face.  It would be better if it detected that and then picked a different port, but I haven't had time yet to work on this.  Any PRs welcome.  : )

Restarting Rodeo will pick another random port, and it'll work.

**Comment by tpaskhalis** [comment]
Not sure that I have the same issue, but it repeatedly fails on startup on Ubuntu 16.04. Doesn't report an uncaught exception, but has something to do with `ipc-promises`.

error: ../opt/Rodeo/resources/app/node/services/ipc-promises:: failed to reply to event 3 checkKernel { executable: '/usr/bin/python',
_[lists Python version and packages]_
cmd: '/usr/bin/python' } 'Error: Object has been destroyed\n    at Error (native)\n    at sendWrapper (/opt/Rodeo/resources/electron.asar/browser/api/web-contents.js:107:24)\n    at /opt/Rodeo/resources/app/node/services/ipc-promises.js:23:22\n    at tryCatcher (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:504:31)\n    at Promise._settlePromise (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:561:18)\n    at Promise._settlePromise0 (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:606:10)\n    at Promise._settlePromises (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/promise.js:685:18)\n    at Async._drainQueue (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:138:16)\n    at Async._drainQueues (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:148:10)\n    at Immediate.Async.drainQueues [as _onImmediate] (/opt/Rodeo/resources/app/node_modules/bluebird/js/release/async.js:17:14)\n    at tryOnImmediate (timers.js:543:15)\n    at processImmediate [as _immediateCallback] (timers.js:523:5)'

**Comment by TakenPilot** [comment]
That log is saying that something between the main process (the one running the python commands) and the browser process (the one drawing in the browser) didn't return a value, but one was expected.

There is probably an error above that which is causing the failure.

**Comment by tpaskhalis** [comment]
The problem seems to have disappeared after reboot, so, unfortunately, I can't provide more details.

**Comment by erikyuzwa** [comment]
https://www.npmjs.com/package/find-port - might be able to make use of this NPM to test a given range of `port` values. I did notice some hard-coded `3001` entries in the `webpack.*` files, but this is also the first time I've really looked at the codebase, so I'm not sure which pieces of the app require the knowledge of the used `port` value.

**Comment by TakenPilot** [comment]
Hey Erik!

Nice idea! You should totally make a PR. :D

Otherwise, I'll add this myself in a bit.

**Comment by erikyuzwa** [comment]
working on it, working on it

**Comment by erikyuzwa** [comment]
speaking of ports, also funny that the issue number is 443.

**Comment by TakenPilot** [comment]
Haha, yeah, good eye.

As a fellow UI developer, I'm really curious about what you think of the rest of the app as well!

**Comment by erikyuzwa** [comment]
:bow: just diving into this codebase but it definitely looks interesting. Electron is EVERYWHERE!! I love it!
https://github.com/yhat/rodeo/pull/564
