### ISSUE TITLE
error when running Rodeo

### ISSUE THREAD

**Issue by crazyhottommy** [yhat/rodeo#56]
Hi, I run Rodeo and some errors occur:       
      
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.2', 'console_scripts', 'rodeo')()
  File "/usr/local/lib/python2.7/site-packages/rodeo/cli.py", line 56, in cmd
    main(active_dir, port=port, host=host, browser=browser)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 109, in main
    kernel = Kernel(plot_dir)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 99, in __init__
    self.client.load_connection_file()
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'/var/folders/h5/3xs5c90n0njgp7n9_qdwwj2m0000gn/T/kernel-40f331b7-7b29-4650-998e-5489d3d587a4.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 91, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/var/folders/h5/3xs5c90n0njgp7n9_qdwwj2m0000gn/T/kernel-40f331b7-7b29-4650-998e-5489d3d587a4.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 91, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/var/folders/h5/3xs5c90n0njgp7n9_qdwwj2m0000gn/T/kernel-40f331b7-7b29-4650-998e-5489d3d587a4.json'

what's wrong? Thanks!
Ming

**Comment by glamp** [comment]
9327375798478ed9446db1f47d1e12bf6e5b1f9c

try the latest version

**Comment by crazyhottommy** [comment]
Thanks, some errors still persist:

Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "/usr/local/lib/python2.7/site-packages/rodeo/cli.py", line 56, in cmd
    main(active_dir, port=port, host=host, browser=browser)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 85, in main
    kernel = Kernel(active_dir)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 81, in __init__
    self.client.load_connection_file()
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'/Users/Tammy/.kernel-23320934-4794-4edf-8289-6986c8b8aa15.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 73, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/Users/Tammy/.kernel-23320934-4794-4edf-8289-6986c8b8aa15.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 73, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/Users/Tammy/.kernel-23320934-4794-4edf-8289-6986c8b8aa15.json'
