### ISSUE TITLE
How to run tensorflow

### ISSUE THREAD

**Issue by phpmind** [yhat/rodeo#565]
My Ipython is working  with Tensorflow and i have used same path in rodeo. 
But here it is showing error. 

I want to run both GPU version and CPU version  code. 

=============================================    ERROR =========================

ImportError: Traceback (most recent call last):
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    frmyuser_john tensorflow.python import pywrap_tensorflow
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow frmyuser_john its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
frmyuser_john there.
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     48     sys.setdlopenflags(_default_dlopen_flags | ctypes.RTLD_GLOBAL)
---> 49     frmyuser_john tensorflow.python import pywrap_tensorflow
     50     sys.setdlopenflags(_default_dlopen_flags)
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>()
     27             return _mod
---> 28     _pywrap_tensorflow = swig_import_helper()
     29     del swig_import_helper
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py in swig_import_helper()
     23             try:
---> 24                 _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
     25             finally:
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py in load_module(name, file, filename, details)
    241         else:
--> 242             return load_dynamic(name, filename, file)
    243     elif type_ == PKG_DIRECTORY:
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py in load_dynamic(name, path, file)
    341             name=name, loader=loader, origin=path)
--> 342         return _load(spec)
    343 
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:
ImportError                               Traceback (most recent call last)
<ipython-input-4-057ddc01dcc5> in <module>()
----> 1 import tensorflow as tf
      2 
      3 hello = tf.constant('Hello, TensorFlow!')
      4 sess = tf.Session()
      5 print(sess.run(hello))
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/__init__.py in <module>()
     22 
     23 # pylint: disable=wildcard-import
---> 24 frmyuser_john tensorflow.python import *
     25 # pylint: enable=wildcard-import
     26 
/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py in <module>()
     58 please exit the tensorflow source tree, and relaunch your python interpreter
     59 frmyuser_john there.""" % traceback.format_exc()
---> 60   raise ImportError(msg)
     61 
     62 # Protocol buffers
ImportError: Traceback (most recent call last):
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    frmyuser_john tensorflow.python import pywrap_tensorflow
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "/hmyuser_johne/myuser_john/anaconda3/envs/tensorflow_3.5/lib/python3.5/imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: libcudart.so.8.0: cannot open shared object file: No such file or directory

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow frmyuser_john its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
frmyuser_john there.

**Comment by TakenPilot** [comment]
It seems the update broke things for you and another person on Github.  I'll remove the update right away.  If you download a older version from [here](https://github.com/yhat/rodeo/releases/tag/v2.4.10), it'll work.

**Comment by phpmind** [comment]
Which old version ?
