### ISSUE TITLE
Problems with conda and Python 3.4

### ISSUE THREAD

**Issue by springcoil** [yhat/rodeo#57]
Hi all,
Excited to see something else cool from Yhat. 
I installed with pip and using anaconda on a Mac. Latest version of anaconda.
Peadars-MBP% rodeo .
Traceback (most recent call last):
  File "/Users/peadarcoyle/anaconda/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py", line 521, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py", line 2632, in load_entry_point
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py", line 2312, in load
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/setuptools-14.3-py3.4.egg/pkg_resources/__init__.py", line 2318, in resolve
  File "/Users/peadarcoyle/anaconda/lib/python3.4/site-packages/rodeo/cli.py", line 30, in <module>
    from rodeo import main
ImportError: cannot import name 'main'

**Comment by springcoil** [comment]
Now I notice there is no 3.4 in the setup.py file - how hard is it to bring it up to Python 3.4 or do I need to just create a virtualenv.

**Comment by finallybiubiu** [comment]
Traceback (most recent call last):
  File "D:\python\Scripts\rodeo-script.py", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "D:\python\lib\site-packages\pkg_resources\__init__.py", line 546, in loa
d_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "D:\python\lib\site-packages\pkg_resources\__init__.py", line 2666, in load_entry_point
    return ep.load()
  File "D:\python\lib\site-packages\pkg_resources\__init__.py", line 2339, in load
    return self.resolve()
  File "D:\python\lib\site-packages\pkg_resources\__init__.py", line 2345, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "D:\python\lib\site-packages\rodeo\cli.py", line 30, in <module>
    from rodeo import main
ImportError: cannot import name 'main'

**Comment by tchakravarty** [comment]
I seem to be getting the same error:
```shell
$ rodeo
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.3', 'console_scripts', 'rodeo')()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 356, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2476, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources.py", line 2190, in load
    ['__name__'])
  File "/usr/local/lib/python3.4/dist-packages/rodeo/cli.py", line 30, in <module>
    from rodeo import main
ImportError: cannot import name 'main'
```

Installed `rodeo` with a `sudo pip3 install rodeo`.

**Comment by springcoil** [comment]
Anyone got anything to comment on this?

**Comment by glamp** [comment]
> Now I notice there is no 3.4 in the setup.py file

What does this mean?

**Comment by springcoil** [comment]
I thought I didn't see Python 3.4 in the Setup.py file. Is this correct?

**Comment by springcoil** [comment]
Actually this works with the newest Rodeo version. No errors my side :) I'll close :)
