### ISSUE TITLE
Rodeo 2.5.2 doesn't install on Windows 7 32-bit

### ISSUE THREAD

**Issue by lihost** [yhat/rodeo#579]
I am unable to install Rodeo 2.5.2(32-bit) on windows 7(32-bit).

Here are my conda install details.

```
(C:\Users\sam\Anaconda3) C:\Users\sam>conda install jupyter_client ipykern
el numpy pandas matplotlib
Fetching package metadata .........
Solving package specifications: ..........

# All requested packages already installed.
# packages in environment at C:\Users\sam\Anaconda3:
#
ipykernel                 4.5.2                    py35_0
jupyter_client            4.4.0                    py35_0
matplotlib                1.5.3               np111py35_1
numpy                     1.11.2                   py35_0
pandas                    0.19.2              np111py35_0

(C:\Users\Deepak\Anaconda3) C:\Users\sam>

```

**Comment by lihost** [comment]
Here is a SquirrelSetup Exception..

```
2017-01-05 14:42:54> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\sam\AppData\Local\rodeo\app-2.5.2\Rodeo.exe]
2017-01-05 14:42:54> ApplyReleasesImpl: Couldn't run Squirrel hook, continuing: C:\Users\sam\AppData\Local\rodeo\app-2.5.2\Rodeo.exe: System.ComponentModel.Win32Exception (0x80004005): The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Squirrel.Utility.<InvokeProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
```

:angry:

**Comment by loukesio** [comment]
I am facing the same issue for long long time :(
