### ISSUE TITLE
Rodeo terminates at start up

### ISSUE THREAD

**Issue by ThomasHolden** [yhat/rodeo#616]
I am running ubuntu 16.04.

I have followed the installation instructions on http://rodeo.yhat.com/docs/#installing-rodeo and subsequently changed the default python path to the Anaconda 3 distribution.

Though when I try to open Rodeo it starts the loading screen but shuts down almost immediately with the following error message:

_error: uncaughtException: watch /home/thomas/nano.save EACCES date=Tue Mar 21 2017 07:58:20 GMT+0100 (CET), pid=24803, uid=1000, gid=1000, cwd=/home/thomas, execPath=/opt/Rodeo/rodeo, version=v6.5.0, argv=[/opt/Rodeo/rodeo], rss=127807488, heapTotal=44167168, heapUsed=30929472, loadavg=[1.17578125, 1.10888671875, 0.85546875], uptime=87854
Error: watch /home/thomas/nano.save EACCES
    at exports._errnoException (util.js:1026:11)
    at FSWatcher.start (fs.js:1439:19)
    at Object.fs.watch (fs.js:1466:11)
    at createFsWatchInstance (/opt/Rodeo/resources/app/node_modules/chokidar/lib/nodefs-handler.js:37:15)
    at setFsWatchListener (/opt/Rodeo/resources/app/node_modules/chokidar/lib/nodefs-handler.js:80:15)
    at FSWatcher.NodeFsHandler._watchWithNodeFs (/opt/Rodeo/resources/app/node_modules/chokidar/lib/nodefs-handler.js:228:14)
    at FSWatcher.NodeFsHandler._handleFile (/opt/Rodeo/resources/app/node_modules/chokidar/lib/nodefs-handler.js:255:21)
    at FSWatcher.<anonymous> (/opt/Rodeo/resources/app/node_modules/chokidar/lib/nodefs-handler.js:473:21)
    at FSReqWrap.oncomplete (fs.js:123:15)_

I have not been able to find a similar issue.

**Comment by cfhammill** [comment]
Same issue on 16.10
