### ISSUE TITLE
ImportError: cannot import name 'main'

### ISSUE THREAD

**Issue by aflyax** [yhat/rodeo#62]
``` bash
$ rodeo
Traceback (most recent call last):
  File "/home/alex/anaconda3/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.0', 'console_scripts', 'rodeo')()
  File "/home/alex/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 546, in load_entry_point
  File "/home/alex/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2666, in load_entry_point
  File "/home/alex/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2339, in load
  File "/home/alex/anaconda3/lib/python3.4/site-packages/setuptools-15.0-py3.4.egg/pkg_resources/__init__.py", line 2345, in resolve
  File "/home/alex/anaconda3/lib/python3.4/site-packages/rodeo/cli.py", line 26, in <module>
    from rodeo import main
ImportError: cannot import name 'main'
```

**Comment by stonebig** [comment]
maybe you should type:
````
rodeo .
````
