### ISSUE TITLE
pkg_resources.DistributionNotFound: ipython>=3.0.0

### ISSUE THREAD

**Issue by martinpllu** [yhat/rodeo#67]
Hey,

On Yosemite, after clean install:

    >  rodeo .
    Traceback (most recent call last):
      File "/usr/local/bin/rodeo", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
        working_set.require(__requires__)
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
        raise DistributionNotFound(req)  # XXX put more info here
    pkg_resources.DistributionNotFound: ipython>=3.0.0
    >  ipython --version
    3.1.0
    >  python --version
    Python 2.7.5

I've tried various methods of clean-reinstalling ipython without avail.

Any ideas?

Thanks,

Martin

**Comment by stonebig** [comment]
You may rather try to update your setuptools and pip module., as pkg_resources is more a setuptools subpackage nowodays.
````
python -m pip install --upgrade pip
python -m pip install --upgrade setuptools
````
(see https://bitbucket.org/pypa/setuptools/src)

**Comment by martinpllu** [comment]
Thanks stonebig, that worked. As a python noob that was pretty non-obvious... really appreciate your help.

**Comment by glamp** [comment]
be8fc1a3ababa0b06eeb9a79533052fdaaa225e3

should help for other people

**Comment by martinpllu** [comment]
Great, that error message will help. Thanks.

**Comment by DavidLGoldberg** [comment]
Got it working after following the above two commands for upgrading pip:

    python -m pip install --upgrade pip
    python -m pip install --upgrade setuptools

**Comment by DavidLGoldberg** [comment]
@glamp I didn't receive the message from the sha above, but rather:

➜  rodeo_tests  rodeo .
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2603, in <module>
    working_set.require(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 666, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 565, in resolve
    raise DistributionNotFound(req)  # XXX put more info here
pkg_resources.DistributionNotFound: mistune
