### ISSUE TITLE
still have errors when run rodeo

### ISSUE THREAD

**Issue by crazyhottommy** [yhat/rodeo#73]
Hi there,

I pip installed the latest version, and there are still errors:
```
Traceback (most recent call last):
  File "/usr/local/bin/rodeo", line 9, in <module>
    load_entry_point('rodeo==0.2.4', 'console_scripts', 'rodeo')()
  File "/usr/local/lib/python2.7/site-packages/rodeo/cli.py", line 60, in cmd
    main(active_dir, port=port, host=host, browser=browser, verbose=verbose)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 114, in main
    kernel = Kernel(active_dir)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 90, in __init__
    self.client.load_connection_file()
  File "/usr/local/lib/python2.7/site-packages/IPython/kernel/connect.py", line 503, in load_connection_file
    with open(self.connection_file) as f:
IOError: [Errno 2] No such file or directory: u'/Users/Tammy/.kernel-d48c6736-4a7e-4fc4-9ac3-7d87f92529ed.json'
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 82, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/Users/Tammy/.kernel-d48c6736-4a7e-4fc4-9ac3-7d87f92529ed.json'
Error in sys.exitfunc:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/2.7.8_2/Frameworks/Python.framework/Versions/2.7/lib/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/rodeo/kernel.py", line 82, in remove_config
    os.remove(config)
OSError: [Errno 2] No such file or directory: '/Users/Tammy/.kernel-d48c6736-4a7e-4fc4-9ac3-7d87f92529ed.json'
```
Thanks,
Ming

**Comment by Claire-** [comment]
Same error has been occured... T_T

**Comment by crazyhottommy** [comment]
sudo rodeo .
seems to work now...

**Comment by ketch** [comment]
I get the same error.  `sudo` does not fix it.

**Comment by chenxiaba** [comment]
seems does't work

**Comment by Claire-** [comment]
Thanks zeroxy! I finally solved the problem, it works well on Windows 7 :D

**Comment by zeroxy** [comment]
@Claire-  My pleasure
