### ISSUE TITLE
Internal Server Error in Rodeo 0.3.0 

### ISSUE THREAD

**Issue by rsmith31415** [yhat/rodeo#87]
After pulling the recent changes in an anaconda environment in Ubuntu 15.04, rodeo stopped working. I created another environment and installed using `pip install -e .` successfully. After starting rodeo, I was required to install `slugify`, but there is another error that is causing an Internal Server Error (`The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.`) in localhost:5000:

```
Created new window in existing browser session.
[ERROR]: Exception on / [GET]
Traceback (most recent call last):
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/user/rodeo_source/rodeo/rodeo.py", line 33, in home
    dirslug = slugify.slugify(dirname)
  File "/home/user/anaconda/envs/rodeo-source-env/lib/python2.7/site-packages/slugify.py", line 26, in slugify
    unicodedata.normalize('NFKD', string)
TypeError: must be unicode, not str
```

**Comment by dyngts** [comment]
Yeah, i got same exact problem here. I think the bug come from slugify where it's mentioned on last line which trying to normalize "NFKD" to string, but throw exception.

**Comment by stonebig** [comment]
try this manually:
https://github.com/yhat/rodeo/issues/90#issuecomment-98790197

**Comment by glamp** [comment]
729d159110fdfd33af1bded56353e02ac6a4e3e9
