### ISSUE TITLE
Unicode error on launch

### ISSUE THREAD

**Issue by rrggrr** [yhat/rodeo#98]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

Python 2.7
On OSX 10.10.3

Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/site-packages/rodeo/rodeo.py", line 71, in home
    file_tree=file_tree, version=__version__)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/site-packages/rodeo/templates/index.html", line 196, in top-level template code
    <a id="file-{{ f.filename }}" data-filename="{{ f.dirname }}/{{f.filename }}" href="#" class="list-group-item openfile {{ f.dirslug }} file">{{ f.filename }}</a>
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 0: ordinal not in range(128)

**Comment by HendryLi** [comment]
meet the same problem too!

**Comment by jimmythekid** [comment]
Anyone have a solution to this?

**Comment by tcliou** [comment]
same problem here.

**Comment by jeanpat** [comment]
me too http://bit.ly/1F8zpS9

**Comment by glamp** [comment]
df824e6ed3d467a303dcd0c6871e18cb7603e4a0
